<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");';

$registry = Zend_Registry::getInstance();
$this->headTitle($registry->site->site->name.' | Activate Your Account');
$this->placeholder('title')->set('Account Activation');
$this->headLink()->appendStylesheet($this->baseUrl().'/_styles/default/screen.css');
$this->headScript()->appendFile($this->baseUrl().'/_scripts/default/common.js','text/javascript')
                   ->appendScript($onloadScript);
?>
<div class="cLWrap">

	<div class="aBox copy nopad">
		
		<h2>Account Activation</h2>
		
	</div>
	
	<p class="Spacer"></p>
	
    <?php echo $this->RenderMessages($this->messages); ?>

</div>

<div class="cRWrap">
				    
	<div class="rBox">
				    	
		<h3>Not a Member?</h3>
				    		
	</div>
				    	
	<p class="Spacer"></p>
				    	
</div>
				    
<p class="ClearAll"></p>
				
