<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.ValidationTextBox");';

$registry = Zend_Registry::getInstance();
$this->headTitle($registry->site->site->name.' | Reset Your Password');
$this->placeholder('title')->set('Login');
$this->headLink()->appendStylesheet($this->baseUrl().'/_styles/default/screen.css');
$this->headScript()->appendFile($this->baseUrl().'/_scripts/default/common.js','text/javascript')
                   ->appendScript($onloadScript);
?>
<div class="cLWrap">

	<div class="aBox copy nopad">
		
		<?php if($this->posted == 'Y') : ?>
		<h2>Password Reset</h2>
		<?php else: ?>
		<h2>Reset Your Password</h2>
		<?php endif; ?>
		
	</div>
	
	<p class="Spacer"></p>
	
	<?php echo $this->RenderMessages($this->messages); ?>
	
	<?php if ($this->posted == 'Y') : ?>
	<?php echo $this->partial('_partials/info.phtml', array('message' => 'Your password has been reset - You should shortly receive an e-mail containing your new password.', 'box' => 'Y')); ?>
	<?php endif; ?>
	
	<div class="aBox copy botpad">
	
		<p>If you have forgotten your password you can use this form to have a new one e-mailed to you.</p>
		
    	<form dojoType="dijit.form.Form" id="passwordForm" jsId="passwordForm" encType="multipart/form-data" action="<?php echo $this->baseUrl();?>/auth/password/" method="POST" class="cForm">
    	
    		<div class="cFormItmH">
    			<label><strong>E-mail address</strong></label><br />
    			<input dojoType="dijit.form.ValidationTextBox" 
        			type="text" 
        			name="email" 
        			value="" 
        			regExp="\b[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b" 
        			trim="true"
        			required="true" 
        			promptMessage="Enter your e-mail address" 
        			invalidMessage="Invalid e-mail address"
        			style="width: 340px;"
        			class="cFormInput"/>
        		<div class="reMarkup">Enter the e-mail address you used when you created your account.</div>
        	</div>
        	
    		<div class="cFormItmS">
    			<button dojoType="dijit.form.Button" type="submit" name="submitButton" value="Reset Password">Reset Password</button>
    		</div>
    		
    	</form>

	</div>
        
	<p class="Spacer"></p>

</div>

<div class="cRWrap">
				    
	<?php echo $this->partial('_partials/noaccountbox.phtml'); ?>
				    	
</div>
				    
<p class="ClearAll"></p>
				
