<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */
?>
<div class="rBox nopad js-on" style="background: url('/_styles/default/images/musicplayer_bg.jpg') no-repeat top left; cursor: pointer;" onClick="wimpyPopPlayer('<?php echo $this->baseUrl();?>/music/player/playlist/all/','485','180'); return false;">
    <h3 style="padding-bottom: 0px; margin-bottom: 0px;"><a href="#" onClick="wimpyPopPlayer('<?php echo $this->baseUrl();?>/music/player/playlist/all/','485','180'); return false;">Open Music Player</a></h3>
</div>

<p class="Spacer js-on"></p>
