<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */
if(!$this->authenticated) : ?>
<div class="rBox">
				    	
    <h3>Sign Up</h3>
		
	<p><a href="<?php echo $this->baseUrl();?>/auth/register/">Register now</a> to add comments to the site and receive the latest news.</p>
	    
    <div class="fauxBut">
        <a href="<?php echo $this->baseUrl();?>/auth/register/">Sign Up</a>
    </div>

<p class="ClearAll"></p>
	
</div>
				    	
<p class="Spacer"></p>
<?php endif; ?>
