<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.form.ComboBox");';

$registry = Zend_Registry::getInstance();
$this->headLink()->appendStylesheet('/_styles/admin/template.css');
$this->headScript()->appendFile('/_scripts/admin/common.js','text/javascript')
                   ->appendScript($onloadScript);

$this->headTitle ( $registry->site->site->name.' Control Panel | Password Reset' );
$this->placeholder('title')->set('Password Reset');
?>
<?php $this->RenderMessages($this->messages); ?>

<?php if ($this->posted == 'Y') : ?>
<?php echo $this->partial('_partials/info.phtml', array('message' => 'Your password has been reset - You should shortly receive an e-mail containing your new password.')); ?>
<?php endif; ?>
    
<form dojoType="dijit.form.Form" id="passwordForm" jsId="passwordForm" encType="multipart/form-data" action="<?php echo $this->baseUrl();?>/admin/auth/password/" method="POST" class="cForm">
    	
    <div class="cFormItmH">
    	<label><strong>E-mail address</strong></label><br />
    	<input dojoType="dijit.form.ValidationTextBox" 
        	type="text" 
        	name="email" 
        	value="" 
        	regExp="\b[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b" 
        	trim="true"
        	required="true" 
        	promptMessage="Enter your e-mail address" 
        	invalidMessage="Invalid e-mail address"
        	style="width: 340px;"
        	class="cFormInput"/>
        <div class="reMarkup">Enter the e-mail address you used when you created your account.</div>
    </div>
        	
    <div class="cFormItmS">
    	<button dojoType="dijit.form.Button" type="submit" name="submitButton" value="Reset Password">Reset Password</button> &nbsp;&nbsp;&nbsp;<a href="<?php echo $this->baseUrl();?>/admin/auth/login/">Login to your account</a>
    </div>
    		
</form>

<p class="ClearAll"></p>
				
