<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

if($this->posted == 'N') : ?>
<?php $this->RenderMessages($this->messages); ?>
<form dojoType="dijit.form.Form" id="mailroleForm" jsId="mailroleForm" encType="multipart/form-data" onSubmit="return doDialog('/admin/mail/mailrole/','mailroleForm','New Mail');" class="cForm" >
    <div class="cFormItm">	
    	<label for="slave"><strong>To Role</strong></label><br />
        <select dojoType="dijit.form.FilteringSelect"
        	name="slave"
        	id="slave"
        	autocomplete="false"
        	style="width: 240px;"
        	value="<?php echo $this->slave; ?>"
        	class="cFormSelect">
    		<?php $this->URoleSelect(); ?>
    	</select>
    </div>
    <div class="cFormItm">
		<label for="url"><strong>Subject</strong></label><br />
        <input dojoType="dijit.form.ValidationTextBox"
        	required="true"
        	trim="true"
            name="subject" 
            type="text" 
            promptMessage="Input a subject"
            invalidMessage="Invalid subject"
            class="cFormInput" 
            id="subject" 
            value="<?php echo $this->subject; ?>" 
            size="55" 
            style="width: 450px;"/>
	</div>
	<p class="ClearAll"></p>
	<div class="cFormDS">
		<button dojoType="dijit.form.Button" 
			type="button" 
			name="newmailsubmitButton" 
			value="Create" 
			iconClass="newmailIcon" 
			onClick="doDialog('/admin/mail/mailrole/','mailroleForm','New Mail');">Create</button>
    	<button dojoType="dijit.form.Button" 
    		type="button" 
    		name="newmailcancelButton" 
    		value="Cancel" 
    		iconClass="cancelIcon" 
    		onClick="dijit.byId('ajaxDialog').hide();">Cancel</button>
    </div>
</form>
<?php endif; ?>