<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */
if ($this->pageCount): ?>

<div class="aNav">

<div class="nButWrapL"><?php echo $this->totalItemCount; ?> Result<?php if($this->totalItemCount > 1) : ?>s<?php endif; ?> - Page <?php echo $this->current; ?> of <?php echo $this->last; ?></div>

<div class="nButWrapR"><!-- Previous page link -->
<?php if (isset($this->previous)): ?>
<a href="<?php echo $this->url(array('page' => $this->previous,'query' => $this->query)); ?>">Previous</a>
<?php else: ?>
<span class="nButN">Previous</span>
<?php endif; ?>

<!-- Numbered page links -->
<?php foreach ($this->pagesInRange as $page): ?>
  <?php if ($page != $this->current): ?>
    <a href="<?php echo $this->url(array('page' => $page,'query' => $this->query)); ?>"><?php echo $page; ?></a>
  <?php else: ?>
    <span class="nButA"><?php echo $page; ?></span>
  <?php endif; ?>
<?php endforeach; ?>

<!-- Next page link -->
<?php if (isset($this->next)): ?>
<a href="<?php echo $this->url(array('page' => $this->next,'query' => $this->query)); ?>">Next</a>
<?php else: ?>
<span class="nButN">Next</span>
<?php endif; ?>

</div>

<p class="ClearAll"></p>
</div>

<?php endif; ?>
