<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Menu");';

$registry = Zend_Registry::getInstance();
$this->headLink()->appendStylesheet('/_styles/admin/template.css');
$this->headScript()->appendFile('/_scripts/admin/common.js','text/javascript')
                   ->appendScript($onloadScript);

$this->headTitle ( $registry->site->site->name.' Control Panel | Rotators | Manage' );
$this->placeholder ( 'title' )->set ( 'Rotators' );
$this->placeholder('section')->set('rotators');
?>

<div dojoType="dijit.Dialog" id="ajaxDialog" title="Information"></div>

<table border="0" width="100%" cellpadding="5" cellspacing="0" id="managetable">
	<tr class="managetablerow">
		<th>Rotator</th>
		<th>Dimensions</th>
		<th>Slides</th>
		<th>Paging</th>
		<th>Delay</th>
	</tr>
	<?php if (count($this->rotatorsArray)) : ?>
    <?php foreach($this->rotatorsArray as $rotator) : ?>
    <?php $class = $this->cycle(array("managetable_row1","managetable_row2"))->next(); ?>
    <tr class="<?php echo $class;?>" onMouseOver="toggleVis('edit<?php echo $rotator['rot_id']; ?>',1); this.className='managetable_highlight';" onMouseOut="toggleVis('edit<?php echo $rotator['rot_id']; ?>',0); this.className='<?php echo $class;?>'">
		<td>
			<strong><a href="/admin/rotators/edit/id/<?php echo $rotator['rot_id']; ?>"><?php echo $rotator['rot_name']; ?></a></strong>
			<div id="edit<?php echo $rotator['rot_id']; ?>" style="visibility:hidden; margin-top: 4px; margin-bottom: 3px;"><a href="<?php echo $this->url(array('action' => 'edit','id' => $rotator['rot_id'])); ?>">Edit</a></div>
		</td>
		<td><?php echo $rotator['rot_width']; ?> x <?php echo $rotator['rot_height']; ?></td>
		<td><?php echo $this->rotSlideCount($rotator['rot_id']); ?></td>
		<td>
			<?php if ($rotator['rot_paging'] == 'Y') : ?>
			<img src="/_styles/admin/icons/tick.gif" alt="Paging Enabled" title="Paging Enabled" border="0" />
			<?php elseif ($rotator['rot_paging'] == 'N') : ?>
			<img src="/_styles/admin/icons/cross.gif" alt="Paging Disabled" title="Paging Disabled" border="0" />
			<?php endif; ?>
		</td>
		<td><?php echo $rotator['rot_delay']; ?></td>
	</tr>
    <?php endforeach; ?>
    <?php else : ?>
    <tr class="managetable_row1">
    	<td colspan="5">
			<div class="cUpd">No Rotators!</div>
		</td>
	</tr>
    <?php endif;?>
</table>

<?php if (count($this->rotatorsArray)) : ?>
<div class="aNav">
    <?php echo $this->paginationControl($this->rotatorsArray,'Sliding','_pagination/default.phtml'); ?>
    <p class="ClearAll"></p>
</div>

<p class="Spacer"></p>
<?php endif; ?>
