<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */
?>
<!-- COMMON SCRIPTS -->

<link rel="shortcut icon" href="<?php echo $this->baseUrl();?>/styles/default/images/favicon.ico" >

<style type="text/css">
	@import "<?php echo $this->baseUrl();?>/styles/default/screen.css";
	@import "<?php echo $this->baseUrl();?>/styles/default/wordcloud.css";
	@import "<?php echo $this->baseUrl();?>/styles/default/frontDij/frontDij.css";
</style>

<script src="<?php echo $this->baseUrl();?>/_scripts/dojo/dojo/dojo.js" djConfig="parseOnLoad: true" type="text/javascript"></script>

<!-- COMMON SCRIPTS -->