<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.SimpleTextarea");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.RotatorContainer");';

$registry = Zend_Registry::getInstance();
$this->headTitle($registry->site->site->name.' | Articles | '.$this->articleArray['article_title']);
$this->placeholder('title')->set('Articles');
$this->placeholder('section')->set('articles');
$this->headLink()->appendStylesheet($this->baseUrl().'/_styles/default/screen.css')
                 ->headLink(array('rel' => 'alternate','type' => 'application/atom+xml','title' => $registry->articles->feedtitle.' (Atom)','href' => $this->baseUrl().'/articles/atom'))
                 ->headLink(array('rel' => 'alternate','type' => 'application/rss+xml','title' => $registry->articles->feedtitle.' (RSS)','href' => $this->baseUrl().'/articles/rss'));
$this->headScript()->appendFile($this->baseUrl().'/_scripts/default/common.js','text/javascript')
                   ->appendScript($onloadScript);
?>
<div class="aBox copy nopad">

	<h2><?php echo $this->escape($this->articleArray['article_title']); ?></h2>

</div>

<p class="Spacer"></p>

<div class="aBox copy <?php if($registry->articles->showauthor == true) : ?>nopad<?php else: ?>toppad<?php endif; ?>">

	<?php if($registry->articles->showauthor == false) : ?>
	<h5 style="padding: 0px;">Written on <?php echo $this->ADate($this->articleArray['article_published']); ?></h5>
	<?php endif; ?>

	<?php echo $this->articleArray['article_intro']; ?>
	<a name="more"></a>
	<?php echo $this->articleArray['article_content']; ?>
	
	<div class="aMore">
		<?php if($this->articleArray['article_comments'] == 'Y') : ?>
		<a href="<?php echo $this->baseUrl();?>/articles/article/<?php echo $this->articleArray['article_id']; ?>/<?php echo urlencode($this->articleArray['article_title']); ?>/#comment">Comment &raquo;</a>
		<?php endif; ?>
		<!-- AddThis Button -->
		<a class="addthis_button" href="http://www.addthis.com/bookmark.php?v=250">Bookmark &amp; Share &raquo;</a>
        <a class="addthis_button_tweet" tm:count="horizontal"></a>
        <a class="addthis_button_facebook_like"></a>
		<script type="text/javascript" src="http://s7.addthis.com/js/250/addthis_widget.js"></script>
		<!-- AddThis Button END -->
	</div>
	
	<div class="aFoot">
		<div class="aFootL">
			<a href="<?php echo $this->baseUrl();?>/articles/article/<?php echo $this->articleArray['article_id']; ?>/<?php echo urlencode($this->articleArray['article_title']); ?>/#comments"><?php $this->CCount($this->articleArray['article_id'],'A'); ?></a>
		</div>
		<div class="aFootR">
			<div class="tagHead">Category:</div><div class="tagList"><a href="<?php echo $this->baseUrl();?>/articles/category/<?php echo urlencode($this->articleArray['acat_title']); ?>/"><?php echo $this->escape($this->articleArray['acat_title']); ?></a></div><br />
			<div class="tagHead">Tags:</div><?php $this->TList($this->articleArray['article_id'],'A','articles'); ?>
		</div>
		<p class="ClearAll"></p>
	</div>
	
</div>

<?php if($registry->articles->showauthor == true) : ?>

<p class="Spacer"></p>

<div class="aBox copy">

	<h5 style="padding: 0px;">Written by <a href="<?php echo $this->baseUrl();?>/articles/author/<?php echo urlencode($this->articleArray['user_alias']); ?>/"><?php echo $this->escape($this->articleArray['user_alias']); ?></a> on <?php echo $this->ADate($this->articleArray['article_published']); ?></h5>
	<?php if($this->articleArray['upro_blurb'] != NULL) : ?><p style="margin-top: 3px; margin-bottom: 3px;"><?php echo $this->BBCode($this->articleArray['upro_blurb']);?></p><?php endif; ?>
	<div class="rMore">
		<a href="<?php echo $this->baseUrl();?>/articles/author/<?php echo urlencode($this->articleArray['user_alias']); ?>/">More articles by <?php echo $this->escape($this->articleArray['user_alias']); ?> &raquo;</a>
	</div>
	<p class="ClearAll"></p>
	
</div>

<?php endif; ?>

<p class="Spacer"></p>

<div class="aBox copy nopad" style="position: relative;">
	<h3><a name="comments">Comments</a></h3>
</div>

<p class="Spacer js-on"></p>

<div dojoType="dijit.layout.ContentPane" id="commentsPane" preload="false" href="/comments/comments/type/A/slave/<?php echo $this->articleArray['article_id']; ?>/" loadingMessage="<span class='dijitContentPaneLoading'></span>" class="js-on"></div>

<noscript>
	<p class="Spacer"></p>
	<div class="aBox copy cInfo">You must have JavaScript enabled to view comments.</div>
	<p class="Spacer"></p>
</noscript>

<?php if($this->articleArray['article_comments'] == 'Y') : ?>
<?php echo $this->partial('_partials/commentform.phtml', array(
    'action' => $this->baseUrl().'/articles/article/'.$this->articleArray['article_id'].'/'.urlencode($this->articleArray['article_title']).'/#comment',
    'moderate' => $this->articleArray['article_moderate'],
    'comment' => $this->comment,
    'auth' => $this->authenticated,
    'acl' => $this->acl->isAllowed($this->role, 'gcommentnew'),
    'messages' => $this->messages)); ?>
<?php endif; ?>
