<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.layout.ContentPane");
dojo.require("dojox.layout.RotatorContainer");';

$registry = Zend_Registry::getInstance();
$this->headTitle($registry->site->site->name.' | Articles | Tags');
$this->placeholder('title')->set('Tags');
$this->placeholder('section')->set('articles');
$this->placeholder('showTags')->set('false');
$this->headLink()->appendStylesheet($this->baseUrl().'/_styles/default/screen.css');
$this->headScript()->appendFile($this->baseUrl().'/_scripts/default/common.js','text/javascript')
                   ->appendScript($onloadScript);
?>
<div class="aBox copy nopad">

	<h2>Tags: Blog</h2>

</div>
<div class="tabBGroup">
	<a href="<?php echo $this->baseUrl();?>/tags/" class="BTab">All (<?php echo $this->TCount('ALL','ALL'); ?>)</a>
	<span class="BTab active">Blog (<?php echo $this->ATagCount('ALL'); ?>)</span>
	<a href="<?php echo $this->baseUrl();?>/pages/tags/" class="BTab">Pages (<?php echo $this->PTagCount('ALL'); ?>)</a>
</div>

<p class="Spacer"></p>

<div class="aBox">

	<?php $this->ATagCloud('articles','ALL'); ?>

</div>

<p class="Spacer"></p>
