<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.form.SimpleTextarea");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dijit.form.CheckBox");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.Menu");
dojo.require("dijit.layout.TabContainer");

var slaveID = "'.$this->venueArray['venue_id'].'";
var slaveLat = "'.$this->venueArray['venue_latitude'].'"
var slaveLng = "'.$this->venueArray['venue_longitude'].'"';

$registry = Zend_Registry::getInstance();
$this->headLink()->appendStylesheet('/_styles/admin/template.css');
$this->headScript()->appendFile('/_scripts/admin/common.js','text/javascript')
                   ->appendFile('http://maps.google.com/maps/api/js?sensor=false','text/javascript')
                   ->appendFile('/_scripts/admin/venue.js','text/javascript')
                   ->appendScript($onloadScript);

$this->headTitle ( $registry->site->site->name.' Control Panel | Events | Edit Venue' );
$this->placeholder ( 'title' )->set ( 'Edit Venue' );
$this->placeholder('section')->set('events');
?>
<?php
include_once('../'.$registry->site->site->publicdir.'/_scripts/fckeditor/fckeditor.php') ;
?>
<div dojoType="dijit.Dialog" id="ajaxDialog" title="Information"></div>

<div dojoType="dijit.layout.ContentPane" id="detailsResponse" preload="true" href="/admin/events/venuedetails?id=<?php echo $this->venueArray['venue_id']; ?>" style="min-height: 50px;"></div>

<div id="mainTabContainer" dojoType="dijit.layout.TabContainer" style="width:100%;" doLayout="false">
	<div id="ContentPane" dojoType="dijit.layout.ContentPane" title="Venue" style="padding: 10px;">

		<form dojoType="dijit.form.Form" id="editForm" method="POST" class="cForm" >

			<div class="cFormItm">
				<label for="title"><strong>Venue Name</strong></label><br />
        		<input dojoType="dijit.form.ValidationTextBox"
        			trim="true"
        			required="true"
        			promptMessage="Enter a venue name"
        			invalidMessage="Invalid venue name"
            		name="title" 
            		type="text" 
            		class="cFormInput" 
            		id="title" 
            		value="<?php echo $this->venueArray['venue_title']; ?>" 
            		size="55" 
            		style="width: 440px;"/>
			</div>
			
			<p class="Spacer"></p>
			
			<div id="mapCanvas" style="width: 470px; height: 350px; float: left; margin-right: 10px; border: 1px solid #CCC;"></div>
			
			<div style="float: left;">
				<div class="cFormItm" style="width: 258px;">
    				<div class="cUpd">You can drag the map marker to fine tune it's location.</div>
    			</div>
				<div class="cFormItm">
					<label for="address"><strong>Latitude</strong></label><br />
        			<input dojoType="dijit.form.TextBox"
            			name="latitude" 
            			type="text" 
            			class="cFormInput" 
            			id="latitude"
            			value="<?php echo $this->venueArray['venue_latitude']; ?>" 
            			size="55" 
            			style="width: 258px;"/>
				</div>
				<div class="cFormItm">
					<label for="address"><strong>Longitude</strong></label><br />
        			<input dojoType="dijit.form.TextBox"
            			name="longitude" 
            			type="text" 
            			class="cFormInput" 
            			id="longitude"
            			value="<?php echo $this->venueArray['venue_longitude']; ?>" 
            			size="55" 
            			style="width: 258px;"/>
				</div>
				<div class="cFormItm">
					<label for="address"><strong>Address</strong></label><br />
        			<input dojoType="dijit.form.SimpleTextarea"
        				trim="true"
        				required="true"
        				promptMessage="Enter an address"
        				invalidMessage="Invalid address"
            			name="address" 
            			type="text" 
            			class="cFormInput" 
            			id="address"
            			value="<?php echo $this->venueArray['venue_address']; ?>" 
            			size="55" 
            			style="width: 258px;"/>
				</div>
				<div class="cFormItm">
					<label for="city"><strong>City</strong></label><br />
        			<input dojoType="dijit.form.ValidationTextBox"
        				trim="true"
        				required="true"
        				promptMessage="Enter a city"
        				invalidMessage="Invalid city"
            			name="city" 
            			type="text" 
            			class="cFormInput" 
            			id="city" 
            			value="<?php echo $this->venueArray['venue_city']; ?>" 
            			size="55" 
            			style="width: 258px;"/>
				</div>
				<div class="cFormItm">
    				<label for="country"><strong>Country</strong></label><br />
    				<select dojoType="dijit.form.FilteringSelect"
        				name="country"
        				id="country"
        				required="true"
        				autocomplete="true"
        				promptMessage="Select a country"
        				invalidMessage="Invalid country"
        				style="width: 200px;"
        				value="<?php echo $this->venueArray['venue_country']; ?>"
        				class="cFormSelect">
        				<option value="#" selected>Pick a Country</option> 
    		        	<?php $this->ecountriesOptions(); ?>
    				</select>
    			</div>
			</div>

			<p class="ClearAll"></p>
			
			<p class="Spacer"></p>
			
			<div class="cFormItm">
    			<label for="description"><strong>Description</strong></label><br />
    	        <?php
                    $FCKeditor = new FCKeditor( 'description' ) ;
			        $FCKeditor->BasePath	= '/_scripts/fckeditor/' ;
			        $FCKeditor->Width	= 760 ;
			        $FCKeditor->Height	= 300 ;
			        $FCKeditor->Value	= $this->venueArray['venue_description'];
			        $FCKeditor->HtmlEncodeOutput = 'false';
                    $FCKeditor->Create() ;
                ?>
    		</div>
    		
    		<p class="ClearAll"></p>
    		
    		<div class="cFormItm">
				<label for="title"><strong>Link</strong></label><br />
        		<input dojoType="dijit.form.ValidationTextBox"
        			trim="true"
        			required="true"
        			promptMessage="Enter a URL"
        			invalidMessage="Invalid URL"
            		name="url" 
            		type="text" 
            		class="cFormInput" 
            		id="url" 
            		regExp="(ftp|http|https):\/\/(\w+:{0,1}\w*@)?(\S+)(:[0-9]+)?(\/|\/([\w#!:.?+=&%@!\-\/]))?"
            		value="<?php echo $this->venueArray['venue_url']; ?>" 
            		size="55" 
            		style="width: 440px;"/>
			</div>
			
			<div class="cFormItmH">
				<label for="title"><strong>E-mail Address</strong></label><br />
        		<input dojoType="dijit.form.ValidationTextBox"
        			trim="true"
        			required="true"
        			promptMessage="Enter an e-mail address"
        			invalidMessage="Invalid e-mail address"
            		name="email" 
            		type="text" 
            		class="cFormInput" 
            		id="email"
            		regExp="\b[a-zA-Z0-9._%-]+@[a-zA-Z0-9.-]+\.[a-zA-Z]{2,4}\b" 
            		value="<?php echo $this->venueArray['venue_email']; ?>" 
            		size="55" 
            		style="width: 320px;"/>
			</div>
			
			<div class="cFormItmH">
				<label for="title"><strong>Phone</strong></label><br />
        		<input dojoType="dijit.form.ValidationTextBox"
        			trim="true"
        			required="true"
        			promptMessage="Enter a phone number"
        			invalidMessage="Invalid phone number"
            		name="phone" 
            		type="text" 
            		class="cFormInput" 
            		id="phone"
            		value="<?php echo $this->venueArray['venue_phone']; ?>" 
            		size="55" 
            		style="width: 160px;"/>
			</div>
    			
		</form>

	</div>
	
</div>