<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */
?>
<table cellspacing="0" cellpadding="0" border="0" width="100%">
	<tr>
		<td valign="top">

			<fieldset class="cFieldset">
				<legend class="cFLegend">Details</legend>
				<span class="tagItm">Account Created: <?php echo $this->MakeDate('d/m/Y',$this->userArray['user_date']); ?></span>
				<span class="tagItm">Last Updated: <?php echo $this->MakeDate('d/m/Y H:i',$this->userArray['upro_date']); ?></span>
				<?php if($this->acl->isAllowed($this->user->user_role, 'gcomments')) : ?><span class="tagItm"><a href="<?php echo $this->url(array('action' => 'manage','controller' => 'comments','author' => $this->userArray['user_id'])); ?>">Comments (<?php $this->CCount($this->userArray['user_id'],'U');?>)</a></span><?php endif; ?>
			</fieldset>

		</td>
	</tr>
</table>	
