<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.form.TextBox");
dojo.require("dijit.form.ValidationTextBox");
dojo.require("dijit.form.FilteringSelect");
dojo.require("dojox.layout.RotatorContainer");
dojo.require("dijit.layout.ContentPane");';

$registry = Zend_Registry::getInstance();
$this->headTitle($registry->site->site->name.' | Account Settings | Password');
$this->placeholder('title')->set('Login');
$this->headLink()->appendStylesheet($this->baseUrl().'/_styles/default/screen.css');
$this->headScript()->appendFile($this->baseUrl().'/_scripts/default/common.js','text/javascript')
                   ->appendFile($this->baseUrl().'/_scripts/default/user.js','text/javascript')
                   ->appendScript($onloadScript);
?>
<div class="cLWrap">

	<div class="aBox copy nopad">
		<h2>Account Settings: Password</h2>
	</div>
	<div class="tabBGroup">
		<a href="<?php echo $this->baseUrl();?>/settings/" class="BTab">Profile</a>
		<span class="BTab active">Password</span>
		<a href="<?php echo $this->baseUrl();?>/settings/subscriptions/" class="BTab">Subscriptions</a>
	</div>
        
	<p class="Spacer"></p>
	
	<?php if ($this->posted != 'N') : ?>
	<?php echo $this->partial('_partials/info.phtml', array('message' => 'Password Changed', 'box' => 'Y')); ?>
	<?php endif; ?>	
	
	<?php if(isset($this->passwordmessage)) : ?>
	<div class="aBox cErr" style="margin-top: 5px;"><?php echo $this->escape($this->passwordmessage); ?></div>
	<p class="Spacer"></p>
	<?php endif; ?>
	
	<?php echo $this->RenderMessages($this->messages); ?>
	
	<div class="aBox nopad">
	
		<form dojoType="dijit.form.Form" id="profileForm" jsId="profileForm" encType="multipart/form-data" action="<?php echo $this->baseUrl();?>/settings/password/" method="POST" class="cForm">
    	
    		<fieldset class="cFieldset">
    			<legend class="cFLegend">Password</legend>
    		
    			<div class="cFormItm">
    				<label for="oldpassword"><strong>Current Password</strong></label><br />
    				<input dojoType="dijit.form.ValidationTextBox"
        				type="password"
        				name="oldpassword" 
        				id="oldpassword"
        				value="" 
        				regExp=".{8}.*" 
        				required="true" 
        				promptMessage="Enter your current password" 
        				invalidMessage="Minimum of 8 characters"
        				class="cFormInput"/>
    			</div>
    			
    			<div class="cFormItmH">
    				<label for="password"><strong>New Password</strong></label><br />
    				<input dojoType="dijit.form.ValidationTextBox"
        				type="password"
        				name="password" 
        				id="password"
        				value="" 
        				regExp=".{8}.*" 
        				required="true" 
        				onblur="passwordCheck(this.value)"
        				promptMessage="Enter a new password" 
        				invalidMessage="Minimum of 8 characters"
        				class="cFormInput"/>
        			<div class="reMarkup">Minimum of 8 characters in length</div>
    			</div>
    		
    			<div class="cFormItmH">
    				<label for="password2"><strong>Confirm New Password</strong></label><br />
    				<input dojoType="dijit.form.ValidationTextBox"
        				type="password"
        				name="password2" 
        				id="password2"
        				value="" 
        				regExp=".{8}.*" 
        				required="true" 
        				promptMessage="Re-enter your new password" 
        				invalidMessage="Passwords don't match"
        				validator="return sameCheck(this, dijit.byId('password'));"
        				style="float: left;"
        				class="cFormInput"/>
        			<div dojoType="dijit.layout.ContentPane" id="passwordResponse" preload="false" style="margin-left: 10px; float: left;"></div>
    			</div>
    			
    		</fieldset>
    		
    		<div class="cFormItmS">
    			<button dojoType="dijit.form.Button" type="submit" name="submitButton" value="Save">Save</button>
    		</div>
    	
    	</form>
	
	</div>
	
	<p class="Spacer"></p>

</div>

<div class="cRWrap">
				    
	<?php echo $this->partial('_partials/searchbox.phtml'); ?>
	
	<?php $this->RenderRotator('SideBar'); ?>
				    	
</div>
				    
<p class="ClearAll"></p>
				
