<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

// Calculate Totals
$areaPlaces = count($this->areaTot);

$locPlaces = count($this->locTot);

// Send the headers
header('Content-type: text/xml; charset="UTF-8"',true); 
header('Pragma: public');        
header('Cache-control: private');
header('Expires: -1');

echo('<?xml version="1.0" encoding="utf-8"?>');
?>
<?php $i = 0; ?>
<markers>
	<?php if (count($this->venuesArray)) : ?>
	<?php foreach ($this->venuesArray as $venue) : ?>
	<?php $eventCount = $this->EMapEventCount($venue['venue_id']);
	if ($eventCount >= 1) : 
	$i++; ?>
	<marker id="<?php echo $venue['venue_id']; ?>" lat="<?php echo $venue['venue_latitude']; ?>" lng="<?php echo $venue['venue_longitude']; ?>">
		<name><![CDATA[<?php echo html_entity_decode($venue['venue_title'],ENT_QUOTES,"UTF-8"); ?>, <?php echo html_entity_decode($venue['venue_city'],ENT_QUOTES,"UTF-8"); ?>, <?php echo html_entity_decode($venue['venue_country'],ENT_QUOTES,"UTF-8"); ?>]]></name>
		<address><![CDATA[<?php echo html_entity_decode($venue['venue_address'],ENT_QUOTES,"UTF-8"); ?>, <?php echo html_entity_decode($venue['venue_city'],ENT_QUOTES,"UTF-8"); ?>, <?php echo html_entity_decode($venue['venue_country'],ENT_QUOTES,"UTF-8"); ?>]]></address>
		<htmldata><![CDATA[
        <?php $this->EMapEventList($venue['venue_id']); ?>
        <p class="Spacer"></p>
        <div class="aMore" style="overflow: hidden;">
			<a href="<?php echo $this->baseUrl();?>/events/venue/<?php echo $venue['venue_id']; ?>/<?php echo urlencode($venue['venue_title']); ?>/" class="tagList">Venue details &raquo;</a><?php if($eventCount > 3) : ?><a href="<?php echo $this->baseUrl();?>/events/venue/<?php echo $venue['venue_id']; ?>/<?php echo urlencode($venue['venue_title']); ?>/#events" class="tagList">More Events &raquo;</a><?php endif; ?>
		</div>
        ]]></htmldata>
	</marker>
	<?php endif; ?>
	<?php endforeach; ?>
	<?php endif; ?>
	<result venues="<?php echo $i;?>"/>
</markers>