<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

echo '<?xml version="1.0" encoding="utf-8" ?>';
echo $this->doctype();
$registry = Zend_Registry::getInstance(); 
?>
<html>

<head>

<!-- META -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta name="robots" content="noindex">
		
<?php echo $this->headTitle(); ?>

<!-- END META -->

<!-- HEAD LINKS -->
<?php echo $this->headLink(); ?>

<!-- END HEAD LINKS -->

<!-- HEAD SCRIPTS -->
<script type="text/javascript" src="/_scripts/dojo/dojo/dojo.js"></script>
<?php echo $this->headScript(); ?>

<!-- END HEAD SCRIPTS -->

<!-- HEAD STYLES -->
<?php echo $this->headStyle(); ?>

<!-- END HEAD STYLES -->

</head>
	
<body class="adminDij">

	<div id="preloader"></div>
	
	<?php echo $this->layout()->content ?>
	    
</body>

</html>
