<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$registry = Zend_Registry::getInstance();
echo '<?xml version="1.0" encoding="utf-8" ?>';
echo $this->doctype() 
?>

<html>

<head>

<!-- META -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
		
<?php echo $this->headTitle(); ?>

<!-- END META -->

<!-- HEAD LINKS -->
<?php echo $this->headLink(); ?>

<link href="<?php echo $this->baseUrl();?>/_styles/default/images/favicon.ico" rel="shortcut icon" >

<!-- END HEAD LINKS -->

<!-- HEAD SCRIPTS -->
<script type="text/javascript" src="/_scripts/dojo/dojo/dojo.js" djConfig="parseOnLoad: true"></script>
<?php echo $this->headScript(); ?>

<!-- END HEAD SCRIPTS -->

<!-- HEAD STYLES -->
<?php echo $this->headStyle(); ?>

<!-- END HEAD STYLES -->
	    
</head>
	
<body>
			
    <?php echo $this->layout()->content ?>
	
</body>

</html>
