<?php
/**
 * LEGACY CMS
 * @author Harry Barnard
 * @version 2.1
 * @copyright Copyright (c) 2010 Harry Barnard (http://harrybarnard.com)
 */

$onloadScript = 'dojo.require("dojo.parser");
dojo.require("dijit.form.Form");
dojo.require("dijit.form.Button");
dojo.require("dijit.Dialog");
dojo.require("dijit.layout.ContentPane");
dojo.require("dijit.layout.TabContainer");';

$registry = Zend_Registry::getInstance();
$this->headLink()->appendStylesheet('/_styles/admin/template.css')
                 ->appendStylesheet('/_styles/admin/icons.css')
                 ->appendStylesheet('/_styles/admin/adminDij/adminDij.css')
                 ->appendStylesheet('/_styles/admin/files.css');
$this->headScript()->appendFile('/_scripts/admin/common.js','text/javascript')
                   ->appendFile('/_scripts/admin/comments.js','text/javascript')
                   ->appendScript($onloadScript);

$this->headTitle ( $registry->site->site->name.' Control Panel | Comments | Manage' );
$this->placeholder ( 'title' )->set ( 'Comments' );
$this->placeholder('section')->set('comments');
?>
<div dojoType="dijit.Dialog" id="ajaxDialog" title="Information"></div>

<fieldset class="cFieldset">
	<legend class="cFLegend">Filter</legend>
				
	<?php if ($this->author != NULL) : ?><span class="tagItm" onmouseover="this.className='tagItm_del';" onmouseout="this.className='tagItm';" onClick="document.location.href='<?php echo $this->baseUrl().$this->url(array('author' => NULL)); ?>';" title="Remove Filter">Author: <?php echo $this->author; ?></span><?php endif; ?>
	<?php if ($this->type != NULL & $this->slave != NULL) : ?><span class="tagItm" onmouseover="this.className='tagItm_del';" onmouseout="this.className='tagItm';" onClick="document.location.href='<?php echo $this->baseUrl().$this->url(array('type' => NULL,'slave' => NULL)); ?>';" title="Remove Filter"><?php $this->cslaveDetails($this->slave,$this->type); ?><?php echo $this->slaveType; ?>: <?php echo $this->slaveTitle; ?></span><?php endif; ?>
    <?php if ($this->author == NULL & $this->type == NULL & $this->slave == NULL) : ?><span class="tagItm">No active filter</span><?php endif; ?>
    			
</fieldset>

<?php if(count($this->commentArray)) : ?>
<?php foreach($this->commentArray as $comment) : ?>
<fieldset class="comFieldset<?php if ($comment['comment_approved'] == 'N') : ?> notapproved<?php endif; ?>" <?php if($this->acl->isAllowed($this->user->user_role, 'gcommentsstatus') | $this->acl->isAllowed($this->user->user_role, 'gcommentdelete')) : ?>onMouseOver="toggleDisp('comedit<?php echo $comment['comment_id']; ?>',1)" onMouseOut="toggleDisp('comedit<?php echo $comment['comment_id']; ?>',0)"<?php endif; ?>>
	<?php if($this->acl->isAllowed($this->user->user_role, 'gcommentsstatus') & $this->acl->isAllowed($this->user->user_role, 'gcommentdelete')) : ?>
	<div class="comEdit" id="comedit<?php echo $comment['comment_id']; ?>" style="display:none;">
		<?php if ($comment['comment_approved'] == 'N') : ?><img src="/_styles/admin/icons/accept.gif" width="16" height="16" align="texttop"/> <a onClick="approveComment(<?php echo $comment['comment_id']; ?>,'Y',0);" title="Approve Comment">Approve</a> | <?php else : ?><img src="/_styles/admin/icons/cross.gif" width="16" height="16" align="texttop"/> <a onClick="approveComment(<?php echo $comment['comment_id']; ?>,'N',0);" title="Disapprove Comment">Disapprove</a> | <?php endif; ?><img src="<?php echo $this->baseUrl();?>/_styles/admin/icons/delete.gif" width="16" height="16" align="texttop"/> <a onClick="deleteComment(<?php echo $comment['comment_id']; ?>,0);" title="Delete Comment">Delete</a>
	</div>
	<?php elseif($this->acl->isAllowed($this->user->user_role, 'gcommentdelete')) : ?>
	<div class="comEdit" id="comedit<?php echo $comment['comment_id']; ?>" style="display:none;">
		<img src="<?php echo $this->baseUrl();?>/_styles/admin/icons/delete.gif" width="16" height="16" align="texttop"/> <a onClick="deleteComment(<?php echo $comment['comment_id']; ?>,0);" title="Delete Comment">Delete</a>
	</div>
	<?php elseif($this->acl->isAllowed($this->user->user_role, 'gcommentsstatus')) : ?>
	<div class="comEdit" id="comedit<?php echo $comment['comment_id']; ?>" style="display:none;">
		<?php if ($comment['comment_approved'] == 'N') : ?><img src="/_styles/admin/icons/accept.gif" width="16" height="16" align="texttop"/> <a onClick="approveComment(<?php echo $comment['comment_id']; ?>,'Y',0);" title="Approve Comment">Approve</a> | <?php else : ?><img src="/_styles/admin/icons/cross.gif" width="16" height="16" align="texttop"/> <a onClick="approveComment(<?php echo $comment['comment_id']; ?>,'N',0);" title="Disapprove Comment">Disapprove</a><?php endif; ?>
	</div>
	<?php endif; ?>
	<div class="comInfo">
		<table class="comInfoTab" border="0" cellspacing="0">
			<tr>
				<th><img src="<?php echo $this->baseUrl();?>/_styles/admin/icons/user.gif" width="16" height="16" /></th>
				<td><a href="<?php echo $this->baseUrl().$this->url(array('author' => $comment['user_id'])); ?>"><?php echo $comment['user_alias']; ?></a></td>
			</tr>
			<tr>
				<th><img src="<?php echo $this->baseUrl();?>/_styles/admin/icons/date.gif" width="16" height="16" align="texttop"/></th>
				<td><?php echo $this->MakeDate('d/m/Y',$comment['comment_date']); ?></td>
			</tr>
		</table>
    </div>
    <strong><?php $this->cslaveDetails($comment['comment_slave'],$comment['comment_type'])?><?php echo $this->slaveType; ?>: <a href="<?php echo $this->baseUrl().$this->url(array('type' => $comment['comment_type'],'slave' => $this->slaveID)); ?>"><?php echo $this->slaveTitle; ?></a></strong>
	<p class="comContent">
	    <?php echo $comment['comment_content']; ?>
	</p>
</fieldset>
<?php endforeach; ?>
<?php else : ?>
<div class="cErr">No Comments!</div>
<?php endif;?>

<?php if(count($this->commentArray)) : ?>
<div class="aNav">
    <?php echo $this->paginationControl($this->commentArray,'Sliding','_pagination/default.phtml'); ?>
    <p class="ClearAll"></p>
</div>

<p class="Spacer"></p>
<?php endif; ?>
